# Generated by Django 5.0.7 on 2024-07-21 12:28

import datetime
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detallesAdicionales',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_adicional',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='fechaSubida',
            field=models.DateField(default=datetime.date(2024, 7, 21)),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to=news.models.news_image_upload_path),
        ),
    ]
