# Generated by Django 5.0.7 on 2024-07-22 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_detallesadicionales_news_youtube_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='fechaSubida',
            field=models.DateField(default=datetime.date(2024, 7, 22)),
        ),
        migrations.AlterField(
            model_name='news',
            name='youtube_adicional',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
