# Generated by Django 5.0.7 on 2024-07-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_fechasubida_alter_news_youtube_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detallesAdicionales',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='youtube_adicional',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
