# Generated by Django 5.0.7 on 2024-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_detallesadicionales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detallesAdicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='youtube_adicional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
